### ISSUE TITLE
Not able to startup / run

### ISSUE THREAD

**Issue by mdaymond** [sararob/video-intelligence-demo#11]
Just trying to install and it seems like there are a few different issues - is there a specific version of node this needs?

```
> appengine-express@0.0.1 start /Users/md/Documents/Dev/video-intelligence-demo/frontend
> node ./bin/www

module.js:471
    throw err;
    ^

Error: Cannot find module 'local.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mikedaymond/Documents/Dev/zonetv/video-intelligence-demo/frontend/app.js:27:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! appengine-express@0.0.1 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appengine-express@0.0.1 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appengine-express package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appengine-express
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appengine-express
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by sararob** [comment]
Thanks for reporting - just deployed a fix. If you pull down the latest master you should be able to run it. You'll notice there's now a `local.json` file in your `frontend/` directory. You should be able to run the frontend without updating the values in `local.json` (you just won't be able to see any videos until you associate it with your project).

**Comment by mdaymond** [comment]
that fixed it .. thanks
