### ISSUE TITLE
GCP ApiError

### ISSUE THREAD

**Issue by JakeBMalis** [sararob/video-intelligence-demo#13]
GET / 304 342.047 ms - -
GET /stylesheets/site.css 200 16.910 ms - 44227
GET /javascripts/compiled.js 200 20.862 ms - 2376367
GET /images/logo.svg 304 0.941 ms - -
GET /favicon.ico 200 58.703 ms - 1004
error getting file { ApiError: Not Found
    at Object.parseHttpRespBody (/Users/jake.malis/Downloads/video-intelligence-demo-master/frontend/node_modules/@google-cloud/common/src/util.js:191:30)
    at Object.handleResp (/Users/jake.malis/Downloads/video-intelligence-demo-master/frontend/node_modules/@google-cloud/common/src/util.js:131:18)
    at /Users/jake.malis/Downloads/video-intelligence-demo-master/frontend/node_modules/@google-cloud/common/src/util.js:465:12
    at Request.onResponse [as _callback] (/Users/jake.malis/Downloads/video-intelligence-demo-master/frontend/node_modules/retry-request/index.js:120:7)
    at Request.self.callback (/Users/jake.malis/Downloads/video-intelligence-demo-master/frontend/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/jake.malis/Downloads/video-intelligence-demo-master/frontend/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
  code: 404,
  errors: [ { domain: 'global', reason: 'notFound', message: 'Not Found' } ],
  response: undefined,
  message: 'Not Found' }

**Comment by mdaymond** [comment]
You should setup a service account and use that in your key.json.

**Comment by JakeBMalis** [comment]
@mdaymond I still tried that but it didn't work.

**Comment by arpitworld** [comment]
any luck with this?

**Comment by JakeMalis** [comment]
I ended up competely restarting the project from scratch and that worked. I think when I was in the process of making it Sara changed the code to make it work better. I'm sorry. Hope this works.
