### ISSUE TITLE
frontend - can't get thumbnail.

### ISSUE THREAD

**Issue by mdaymond** [sararob/video-intelligence-demo#14]
Getting jquery.js?27d9:3860 jQuery.Deferred exception: Cannot read property 'thumbnail' of undefined TypeError: Cannot read property 'thumbnail' of undefined

${VIDEO_DATA[video.url_safe_id].thumbnail}

**Comment by JakeBMalis** [comment]
I don't know why, but when I run the app it is getting the JSON, but wont show the video with the annotations visualized.

**Comment by mdaymond** [comment]
Look at the console in your browser.  I think there is an issue with image previews.  If you make the preview variable an empty string in the front end that should fix it.

**Comment by JakeBMalis** [comment]
In the console in my browser, there are no errors. How would I make the preview variable an empty string.

**Comment by EmilAvalon** [comment]
Have the same. In Chrome error bug:
dog:12 Uncaught TypeError: Cannot read property 'thumbnail' of undefined
    at exports.default (eval at <anonymous> (https://xxxxxxxxxxxx.appspot.com/javascripts/compiled.js:95:2), <anonymous>:12:57)
    at eval (eval at <anonymous> (https://xxxxxxxxxxxxx.appspot.com/javascripts/compiled.js:107:2), <anonymous>:187:40)
    at Array.map (native)
    at SearchPage.renderResultCards (eval at <anonymous> (https://xxxxxxxxxxxxxx.appspot.com/javascripts/compiled.js:107:2), <anonymous>:186:33)
    at SearchPage.render (eval at <anonymous> (https://xxxxxxxxxxxx.appspot.com/javascripts/compiled.js:107:2), <anonymous>:89:14)
    at new SearchPage (eval at <anonymous> (https://xxxxxxxxx.appspot.com/javascripts/compiled.js:107:2), <anonymous>:52:10)
    at App.renderPage (eval at <anonymous> (https://xxxxxxxxxxxxx.appspot.com/javascripts/compiled.js:47:2), <anonymous>:146:30)
    at searchQuery (eval at <anonymous> (https://xxxxxxxxxx.appspot.com/javascripts/compiled.js:47:2), <anonymous>:125:17)
    at eval (eval at <anonymous> (https://xxxxxxxxxxxx.appspot.com/javascripts/compiled.js:77:2), <anonymous>:321:125)
    at manageHooks (eval at <anonymous> (https://xxxxxxxxxx.appspot.com/javascripts/compiled.js:77:2), <anonymous>:210:4)

**Comment by EmilAvalon** [comment]
I found workaround. 
1. Edit  frontend/resources/js/components/video-card.js
2. comment line const preview = VIDEO_...... 
3. Create bucket and replace bucket_name in line 5
4. create png file called sample-mp4.png 
5. Add line const preview = 'https://storage.googleapis.com/**[bucket_name**]/sample-mp4.png';
6. save
7. Go back to frontend dir
8. npm install

**Comment by sararob** [comment]
I fixed this in the latest commit, let me know if you're still having issues.
