### ISSUE TITLE
Error getting file. ApiError

### ISSUE THREAD

**Issue by JakeBMalis** [sararob/video-intelligence-demo#15]
GET /favicon.ico 304 443.125 ms - -
GET / 304 70.205 ms - -
GET /stylesheets/site.css 304 3.304 ms - -
GET /javascripts/compiled.js 304 3.840 ms - -
GET /images/logo.svg 304 0.406 ms - -
GET /favicon.ico 200 44.792 ms - 1004
{ kind: 'storage#object',
  id: 'video-intelligence-json/google-home-superbowlmp4.json/1492345772494061',
  selfLink: 'https://www.googleapis.com/storage/v1/b/video-intelligence-json/o/google-home-superbowlmp4.json',
  name: 'google-home-superbowlmp4.json',
  bucket: 'video-intelligence-json',
  generation: '1492345772494061',
  metageneration: '1',
  contentType: 'application/json',
  timeCreated: '2017-04-16T12:29:32.443Z',
  updated: '2017-04-16T12:29:32.443Z',
  storageClass: 'MULTI_REGIONAL',
  timeStorageClassUpdated: '2017-04-16T12:29:32.443Z',
  size: '40178',
  md5Hash: 'O15kbUixMKzQM41DOAhG/A==',
  mediaLink: 'https://www.googleapis.com/download/storage/v1/b/video-intelligence-json/o/google-home-superbowlmp4.json?generation=1492345772494061&alt=media',
  crc32c: 'D1ouWQ==',
  etag: 'CO2Zm539qNMCEAE=' }
error getting file { ApiError: Not Found
    at Object.parseHttpRespBody (/Users/jake.malis/Documents/video-intelligence-demo/frontend/node_modules/@google-cloud/common/src/util.js:191:30)
    at Object.handleResp (/Users/jake.malis/Documents/video-intelligence-demo/frontend/node_modules/@google-cloud/common/src/util.js:131:18)
    at /Users/jake.malis/Documents/video-intelligence-demo/frontend/node_modules/@google-cloud/common/src/util.js:465:12
    at Request.onResponse [as _callback] (/Users/jake.malis/Documents/video-intelligence-demo/frontend/node_modules/retry-request/index.js:120:7)
    at Request.self.callback (/Users/jake.malis/Documents/video-intelligence-demo/frontend/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/jake.malis/Documents/video-intelligence-demo/frontend/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
  code: 404,
  errors: [ { domain: 'global', reason: 'notFound', message: 'Not Found' } ],
  response: undefined,
  message: 'Not Found' }
/Users/jake.malis/Documents/video-intelligence-demo/fronten

**Comment by Ganesh-koramangala** [comment]
Hi, i have the same issue and i see the issue is closed. How did you resolve this?

@sararob any thoughts??

{
 insertId:  "1c0apxgg4hch7vl"  
 labels: {
  appengine.googleapis.com/instance_name:  "aef-default-20180306t131145-wjg4"   
  compute.googleapis.com/resource_id:  "2152159602587952184"   
  compute.googleapis.com/resource_name:  "4ecedc01c3b5"   
  compute.googleapis.com/zone:  "us-east1-d"   
 }
 logName:  "projects/vision-197202/logs/appengine.googleapis.com%2Fstdout"  
 receiveTimestamp:  "2018-03-07T02:41:14.530972444Z"  
 resource: {
  labels: {
   module_id:  "default"    
   project_id:  "vision-197202"    
   version_id:  "20180306t131145"    
  }
  type:  "gae_app"   
 }
 textPayload:  "error getting file { ApiError: Not Found
    at Object.parseHttpRespBody (/app/node_modules/@google-cloud/common/src/util.js:191:30)
    at Object.handleResp (/app/node_modules/@google-cloud/common/src/util.js:131:18)
    at /app/node_modules/@google-cloud/common/src/util.js:465:12
    at Request.onResponse [as _callback] (/app/node_modules/retry-request/index.js:120:7)
    at Request.self.callback (/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
"  
 timestamp:  "2018-03-07T02:41:12Z"  
}

**Comment by arpitworld** [comment]
any luck here?
