### ISSUE TITLE
video.VideoIntelligenceServiceClient is not a constructor

### ISSUE THREAD

**Issue by quochuypho** [sararob/video-intelligence-demo#24]
I'am trying to deploy analyzeVideo for the backend
and installed npm --save install @google-cloud/video-intelligence

Deploying function (may take a while - up to 2 minutes)...failed.
ERROR: (gcloud.beta.functions.deploy) OperationError: code=3, message=Function l
oad error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: video.VideoIntelligenceServiceClient is not a c
onstructor
    at Object.<anonymous> (/user_code/index.js:29:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getUserFunction (/var/tmp/worker/worker.js:373:24)
    at loadUserCode (/var/tmp/worker/worker.js:429:18)

D:\Documents\Programmation\Video Intelligene API\Video Intelligence\video-intell
igence-demo\backend>

**Comment by quochuypho** [comment]
i have found out: update the npm package google-cloud/video-intelligence that is required to 1.0.0

and the constructor VideoIntelligenceServiceClient will be found

**Comment by 4ddm** [comment]
I am new here and to coding, but really wanted to try and get this project working. Followed it to the letter but getting the error as above an nothing I try resolves. Please help someone... I don't want to just give up.

Deployment failure:
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: video.VideoIntelligenceServiceClient is not a constructor
    at Object.<anonymous> (/user_code/index.js:22:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at getUserFunction (/var/tmp/worker/worker.js:388:24)
    at loadUserCode (/var/tmp/worker/worker.js:444:18)

**Comment by machiq** [comment]
I ran into the same issue.  

@quochuypho  solution fixed _this_ error.  There were a couple more to overcome after resolving this one.

Have you tried his solution?
`npm --save install @google-cloud/video-intelligence`

**Comment by 4ddm** [comment]
Yes, have tried that sadly. Have seen some examples where reverence to the version is made in the code. If I do that it changes the error.
