### ISSUE TITLE
Error: spawn ENOTDIR on Cloud Functions

### ISSUE THREAD

**Issue by af001** [sararob/video-intelligence-demo#27]
If anyone knows how to fix this any help is appreciated. Pushing it to Google Functions works, but when generateThumbnail and generatePreview run I get this error. I've tried different packages, and I do have ffmpeg and ffprobe in my project path when I push to Google Functions. 

```
Error: spawn ENOTDIR
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:328:11)
    at exports.spawn (child_process.js:369:9)
    at /user_code/node_modules/fluent-ffmpeg/lib/ffprobe.js:155:21
    at FfmpegCommand.proto._getFfprobePath (/user_code/node_modules/fluent-ffmpeg/lib/capabilities.js:144:14)
    at FfmpegCommand.proto.ffprobe (/user_code/node_modules/fluent-ffmpeg/lib/ffprobe.js:141:10)
    at getMetadata (/user_code/node_modules/fluent-ffmpeg/lib/recipes.js:160:14)
    at computeTimemarks (/user_code/node_modules/fluent-ffmpeg/lib/recipes.js:175:11)
    at nextTask (/user_code/node_modules/fluent-ffmpeg/node_modules/async/dist/async.js:5310:14)
    at Object.waterfall (/user_code/node_modules/fluent-ffmpeg/node_modules/async/dist/async.js:5320:5)
```

**Comment by af001** [comment]
Finally found a solution! To share:

```
const ffmpegPath = require('@ffmpeg-installer/ffmpeg').path;
const ffprobePath = require('@ffprobe-installer/ffprobe').path;
const ffmpeg = require('fluent-ffmpeg');
const rimraf = require('rimraf');

ffmpeg.setFfmpegPath(ffmpegPath);
ffmpeg.setFfprobePath(ffprobePath);
```
