### ISSUE TITLE
frontend failing: jQuery.Deferred exception: Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by allenday** [sararob/video-intelligence-demo#31]
It's unclear how to debug this as the code is webpacked.

Simply loading `http://localhost:8080/` produces this error.
`http://localhost:8080/profile` also fails.

```
jQuery.Deferred exception: Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined
    at new App (eval at <anonymous> (http://localhost:8080/javascripts/compiled.js:47:2), <anonymous>:83:25)
    at HTMLDocument.eval (eval at <anonymous> (http://localhost:8080/javascripts/compiled.js:47:2), <anonymous>:243:3)
    at mightThrow (eval at <anonymous> (http://localhost:8080/javascripts/compiled.js:53:2), <anonymous>:3534:29)
    at process (eval at <anonymous> (http://localhost:8080/javascripts/compiled.js:53:2), <anonymous>:3602:12) undefined
```

**Comment by allenday** [comment]
this is probably the same as issue #29

**Comment by ghost** [comment]
the same error both localy and deployed app
jquery.js?27d9:3827 Uncaught TypeError: Cannot read property 'get' of undefined
    at new App (eval at <anonymous> (compiled.js:47), <anonymous>:83:25)
    at HTMLDocument.eval (eval at <anonymous> (compiled.js:47), <anonymous>:243:3)
    at mightThrow (eval at <anonymous> (compiled.js:53), <anonymous>:3534:29)
    at process (eval at <anonymous> (compiled.js:53), <anonymous>:3602:12)

could anybody solve this issue?

**Comment by ghost** [comment]
@allenday 
Hi ,could you find a solution for this issue? I have the same issue in both app deploy and local.
