### ISSUE TITLE
GeneratePreview - Error: spawn /user_code/ffmpeg/ffprobe ENOENT at exports._errnoException

### ISSUE THREAD

**Issue by andscova** [sararob/video-intelligence-demo#33]
Hello,

I'm getting this error:

Error: spawn /user_code/ffmpeg/ffprobe ENOENT at exports._errnoException (util.js:1020:11) at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32) at onErrorNT (internal/child_process.js:376:16) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickDomainCallback (internal/process/next_tick.js:128:9)

{
 insertId:  "000000-8b4b5756-d5fb-46eb-99f4-d0e68def4ec2"  
 labels: {…}  
 logName:  "projects/xxxxx/logs/cloudfunctions.googleapis.com%2Fcloud-functions"  
 receiveTimestamp:  "2018-07-19T12:21:49.648936274Z"  
 resource: {…}  
 severity:  "ERROR"  
 textPayload:  "Error: spawn /user_code/ffmpeg/ffprobe ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"  
 timestamp:  "2018-07-19T12:21:43.040Z"  
}

Could you please advice?

Best,

a.

**Comment by andscova** [comment]
At the same time I'm also getting:

generatePreview
(node:2) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead

{
 insertId:  "000000-6e479fed-6820-4000-8252-61d7b50d2019"  
 labels: {…}  
 logName:  "projects/xxxx/logs/cloudfunctions.googleapis.com%2Fcloud-functions"  
 receiveTimestamp:  "2018-07-19T12:21:43.193604810Z"  
 resource: {…}  
 severity:  "ERROR"  
 textPayload:  "(node:2) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead"  
 timestamp:  "2018-07-19T12:21:36.658Z"  
}

**Comment by leo-mao** [comment]
here is my solution:
```
cd backend/
npm i @grpc/proto-loader
npm i fluent-ffmpeg
# also, make sure you installed the newest beta version of Video Intelligence
npm i @google-cloud/video-intelligence@1.2.0
```

**Comment by andscova** [comment]
That should be ok, not sure what's going on, I'll try again from scratch with all deps:

```
backend andscova$ npm show @google-cloud/video-intelligence version
1.2.0
backend andscova$ npm show @grpc/proto-loader version
0.3.0
backend andscova$ npm show fluent-ffmpeg version
2.1.2
```

**Comment by ghost** [comment]
@andscova it helps you!

const ffmpeg = require('fluent-ffmpeg');

const ffmpegPath = require('@ffmpeg-installer/ffmpeg').path;
const ffprobePath = require('@ffprobe-installer/ffprobe').path;
const rimraf = require('rimraf');

ffmpeg.setFfmpegPath(ffmpegPath);
ffmpeg.setFfprobePath(ffprobePath);

**Comment by hashkanna** [comment]
@shoreshgithub your solution helped to fix the problem. Thanks. I also had to update the package.json to include @ffmpeg-installer/ffmpeg and @ffprobe-installer/ffprobe
